apiVersion: v1
kind: Secret
metadata:
  namespace: upbound-system
  name: example-provider-secret
type: Opaque
data:
  credentials: dGVzdA==
---
apiVersion: gps.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: example-provider-secret
      key: credentials