apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xships-dummy
  labels:
    provider: dummy
spec:
  compositeTypeRef:
    apiVersion: logistics.example.com/v1alpha1
    kind: XShip
  resources:
  - name: bucket1
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          acl: public-read-write
          locationConstraint: us-east-1
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.parameters.bucketName"
      toFieldPath: "metadata.name"
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.lng
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.lat