apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xships-dummy
  labels:
    provider: dummy
spec:
  compositeTypeRef:
    apiVersion: logistics.example.com/v1alpha1
    kind: XShip
  resources:
  - name: bucket
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          acl: public-read-write
          locationConstraint: us-east-1
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.parameters.bucketName"
      toFieldPath: "metadata.name"
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.lng
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.lat
  - name: somesensor
    base:
      apiVersion: nop.crossplane.io/v1alpha1
      kind: NopResource
      metadata:
        name: somesensor
      spec:
        forProvider:
          conditionAfter:
            - conditionType: "Ready"
              conditionStatus: "True"
              time: "3s"
            - conditionType: "Synced"
              conditionStatus: "True"
              time: "1s"
