apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123456
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123457
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123458
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123459
  labels:
    terminal: copenhagen
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123460
  labels:
    terminal: copenhagen
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123461
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123462
spec:
  parameters:
---
apiVersion: logistics.example.com/v1alpha1
kind: Truck
metadata:
  name: truck-123463
spec:
  parameters:
---
