apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcontainers.logistics.example.com
spec:
  group: logistics.example.com
  names:
    kind: XContainer
    plural: xcontainers
  claimNames:
    kind: Container
    plural: containers
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object