apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xships-dummy
  labels:
    provider: dummy
spec:
  compositeTypeRef:
    apiVersion: logistics.example.com/v1alpha1
    kind: XShip
  resources:
  - name: somesensor
    base:
      apiVersion: nop.crossplane.io/v1alpha1
      kind: NopResource
      metadata:
        name: somesensor
      spec:
        forProvider:
          conditionAfter:
            - conditionType: "Ready"
              conditionStatus: "True"
              time: "3s"
            - conditionType: "Synced"
              conditionStatus: "True"
              time: "1s"
  - name: gps
    base:
      apiVersion: sample.gps.crossplane.io/v1alpha1
      kind: VesselGpsType
      spec:
        providerConfigRef:
          name: example
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.lng
      toFieldPath: status.lng
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.lat
      toFieldPath: status.lat
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.imo
      toFieldPath: spec.forProvider.imo