apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtrucks.logistics.example.com
spec:
  group: logistics.example.com
  names:
    kind: XTruck
    plural: xtrucks
  claimNames:
    kind: Truck
    plural: trucks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object